// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjzzjhgjxsfbbwwuqcxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqenpqaGdqeHNmYmJ3d3VxY3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzOTA1NDAsImV4cCI6MjA3Nzk2NjU0MH0.q3-ufNK2DejfLPB_oWPW1ytEGNIae6OljpU9GpbEUy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});